CREATE TABLE USERS(
	ID integer PRIMARY KEY AUTOINCREMENT,
	USER_NAME text,
	ADDRESS text,
	JOIN_DATE integer,
	ENTERED DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE STATUS_UPDATES(
	ID integer PRIMARY KEY AUTOINCREMENT,
	ID_USERS integer,
	USER_STATUS text,
	ENTERED DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE GROUPS(
	ID integer PRIMARY KEY AUTOINCREMENT,
	ID_USERS integer,
	GROUP_NAME text,
	PUBLIC_GROUP text,
	ENTERED DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE LINK_USER_GROUP(
	ID integer PRIMARY KEY AUTOINCREMENT,
	ID_USERS integer,
	ID_GROUPS integer,
	ENTERED DATETIME DEFAULT CURRENT_TIMESTAMP);

.save FAKEFACEBOOK.db
